import { Typography } from '@/components';
import type { Metadata } from 'next';
import { inter } from './fonts/font-config';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Typography fontSkin="body-subtle-small">From Layout</Typography>
        {children}
      </body>
    </html>
  );
}
